name: esp32_cam_viewer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  image: ^3.2.0
  webview_flutter: ^4.10.0
  wakelock_plus: ^1.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
